### ISSUE TITLE
how to change the =Title

### ISSUE THREAD

**Issue by Alvazz** [Fermium/AltiumTemplates#1]
Hi Fermium,

I use github client for clone this repo. and follow the Readme.md file to operation. but I dont know how set the value such as =Title and Author infomation....blablala....

can you tech me how can I modify it.

**Comment by ddavidebor** [comment]
Hi @Alvazz,

These are parameters you can edit through the properties panel. Just make sure you didn't select any object.

**Comment by jbacon23** [comment]
Hello, how do I change the logo? I can't find the parameter for it so it's stuck on "your logo here"
Thanks

**Comment by ddavidebor** [comment]
You have to edit the image object replacing the image

**Comment by jbacon23** [comment]
Thanks,
It was in the A3 file, that's why I couldn't edit it in the higher level
template or my own page.
